### ISSUE TITLE
Add "jayhacks-2017" as a topic

### ISSUE THREAD

**Issue by stefanmendoza** [sushil-bharati/jayhacks2017#2]
You should add "jayhacks-2017" as a topic for the repo under the description! That way it's easy to find all the projects!

**Comment by sushil-bharati** [comment]
Thank you for your suggestion. Done.

**Comment by stefanmendoza** [comment]
@sushil-bharati Awesome. Thanks and good job at the hackathon!

**Comment by sushil-bharati** [comment]
Thanks @stefanmendoza for the heads up. We did our best. Did not win even the top 3. We are still wondering why :(
